config/routes.rb
Rails.application.routes.draw do
  get 'profiles/show'

  get 'profiles/edit'

  get 'profiles/update'

  root to: "static_pages#landing"

  get "/login", to: "sessions#new"
  delete "/logout", to: "sessions#destroy"

  get "/auth/and_me/callback", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  get "/neanderthal", to: "users#neanderthal"

  get "/profile", to: "profiles#show"
  get "/profile/edit", to: "profiles#edit"
end

app/models/neanderthal.rb
class Neanderthal < OpenStruct

end

app/models/population.rb
class Population
  def initialize(name, info)
    @name = name
    @info = info
  end
end

app/models/profile.rb
class Profile < OpenStruct
  def initialize(current_user)
    @current_user = current_user
  end

  def self.service
    ProfileService.new(current_user.token)
  end

  def self.picture_sm
    service.picture_sm
  end

  def self.picture_lg
    service.picture_lg
  end

  def self.maternal_haplogroup
    service.maternal_haplogroup
  end

  def self.paternal_haplogroup
    service.paternal_haplogroup
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  def self.from_omniauth(user_info)
    binding.pry
    where(and_me_id: user_info[:profile_id]).first_or_create do |new_user|
      new_user.access_token  = token
      new_user.email         = user_info[:email]
      new_user.and_me_id     = user_info[:profile_id]
      new_user.first_name    = user_info[:first_name]
    end
  end
end

app/controllers/and_me_oauth_controller.rb
class AndMeOauthController < ApplicationController
  def receive_code
    AndMeService.new(params)
    # uri = URI("https://api.23andme.com/token")
    #   param_code = params[:code]
    #   token_params = {
    #     "client_id" => ENV["23_id"],
    #     "client_secret" => ENV["23_secret"],
    #     "grant_type" => "authorization_code",
    #     "code" => param_code,
    #     "redirect_uri" => "http://localhost:3000/receive_code",
    #     "scope" => "basic haplogroups email ancestry",
    #   }
    #
    #   response = JSON.parse(Net::HTTP.post_form(uri, token_params).body)
    #   token = response["access_token"]
      # call = `curl https://api.23andme.com/1/neanderthal/profile_id -H "Authorization: Bearer #{token}"`
      redirect_to root_path

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @user = current_user
    @profile = Profile.new(@user)
  end

  def edit
  end

  def update
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    binding.pry
    if user = User.from_omniauth(request.env["omniauth.auth"])
        session[:user_id] = user.id
      end
      redirect_to root_path
  end

  def destroy
    session.clear
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def landing
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def neanderthal
    @neanderthal = NeanderthalService.new(current_user.access_token, current_user).neanderthal_info
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def email_address(token)
    UserService.new(token).email
  end

  def first_name(token)
    UserService.new(token).first_name
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ApiCurious</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1"></head>
<body>
  <%= render partial: "partials/header" %>
  <%= yield %>

</body>
</html>

app/views/partials/_header.html.erb
<header>
  <div class="navbar navbar-top">
    <div class="container">
      <div class="navbar-brand">
        <%= link_to "23andMe Genetic Explorer", root_path %>
      </div>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home", root_path %></li>

          <% if current_user %>
            <li><%= link_to "Neanderthal Profile", neanderthal_path  %></li>
            <li role="presentation" class="dropdown"><%= render partial: "/partials/user_dropdown" %></li>
            <li><%= link_to "Logout", logout_path, method: :delete %></li>

          <% else %>
            <li><%= link_to "How it works", root_path %></li>
            <li><%= link_to "Stories", root_path %></li>
            <li><%= link_to "Research", root_path %></li>
            <li><%= link_to "Buy", root_path %></li>
            <li><%= link_to "Sign in with 23andMe", "https://api.23andme.com/authorize/?redirect_uri=http://localhost:3000/auth/and_me/callback&response_type=code&client_id=fa14c16e8d247c33723730c697802dd9&scope=basic%20genomes" %></li>

          <% end %>
        </ul>
      </div>
    </div>
  </div>
</header>

app/views/partials/_user_dropdown.html.erb
<a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
  <%= current_user.first_name %><span class="caret"></span>
</a>
<ul class="dropdown-menu">
  <li><%= link_to "View Profile", profile_path %></li>
  <li><%= link_to "Browse Raw Data", root_path %></li>
</ul>

app/views/profiles/edit.html.erb
<h1>ProfilesController#edit</h1>
<p>Find me in app/views/profiles_controller/edit.html.erb</p>

app/views/profiles/show.html.erb
<div class="container">
    <h3>My Profile</h3>
</div>

<div class="profile container">
  <ul class="nav nav-pills">
    <li role="presentation" class="active"><a href="#">View Profile</a></li>
    <li role="presentation"> <%= link_to "Edit Profile", profile_edit_path %></li>
  </ul>
  <h4>View Profile</h4>

  <h5>This is what your genome sharing connections and non-anonymous DNA Relatives connections will see when they view your profile.</h5>
  <div class="">
    <%= image_tag @profile.picture_lg, class: "img-rounded img-responseive"%>
    <%= @user.first_name + " " + @user.last_name %>
  </div>
  <div class="col-md-5">
    <p>Maternal Haplogroup: <%= @profile.maternal_haplogroup %></p>
    <p>Paternal Haplogroup: <%= @profile.paternal_haplogroup %></p>
  </div>
</div>



</div>

app/views/profiles/update.html.erb
<h1>ProfilesController#update</h1>
<p>Find me in app/views/profiles_controller/update.html.erb</p>

app/views/static_pages/landing.html.erb
<div class="container">
    <h1>Welcome to 23 and Me Genetic Explorer</h1>
</div>

app/views/users/ancestry.html.erb
  <div class="container">
    <h1>Ancestry Profile</h1>
    <div class="jumbotron">
      <%= @presenter.ancestry_info %>
    </div>
  </div>

app/views/users/neanderthal.html.erb
<div class="container">
  <h1>Neanderthal Profile</h1>
  <div class="jumbotron">
    <h3>
      Estimated genome-wide proportion of Neanderthal ancestry for the user's profile. Most users have between 0.01 and 0.04 Neanderthal ancestry.
    </h3>
    <table class="table table-striped">
      <tr>
        <td>Neanderthal Proportion:</td>
        <td><%= @neanderthal.proportion %></td>
      </tr>
      <tr>
        <td>Average Proportion:</td>
        <td><%= @neanderthal.average %></td>
      </tr>
      <tr>
        <td>Ancestry:</td>
        <td><%= @neanderthal.label %></td>
      </tr>
    </table>
  </div>
</div>